/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/message.pb-c.h"
void   device_information_request__init
                     (DeviceInformationRequest         *message)
{
  static const DeviceInformationRequest init_value = DEVICE_INFORMATION_REQUEST__INIT;
  *message = init_value;
}
size_t device_information_request__get_packed_size
                     (const DeviceInformationRequest *message)
{
  assert(message->base.descriptor == &device_information_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_information_request__pack
                     (const DeviceInformationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_information_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_information_request__pack_to_buffer
                     (const DeviceInformationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_information_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceInformationRequest *
       device_information_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceInformationRequest *)
     protobuf_c_message_unpack (&device_information_request__descriptor,
                                allocator, len, data);
}
void   device_information_request__free_unpacked
                     (DeviceInformationRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_information_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   device_information_response__init
                     (DeviceInformationResponse         *message)
{
  static const DeviceInformationResponse init_value = DEVICE_INFORMATION_RESPONSE__INIT;
  *message = init_value;
}
size_t device_information_response__get_packed_size
                     (const DeviceInformationResponse *message)
{
  assert(message->base.descriptor == &device_information_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_information_response__pack
                     (const DeviceInformationResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_information_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_information_response__pack_to_buffer
                     (const DeviceInformationResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_information_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceInformationResponse *
       device_information_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceInformationResponse *)
     protobuf_c_message_unpack (&device_information_response__descriptor,
                                allocator, len, data);
}
void   device_information_response__free_unpacked
                     (DeviceInformationResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_information_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_color_mode_request__init
                     (SetColorModeRequest         *message)
{
  static const SetColorModeRequest init_value = SET_COLOR_MODE_REQUEST__INIT;
  *message = init_value;
}
size_t set_color_mode_request__get_packed_size
                     (const SetColorModeRequest *message)
{
  assert(message->base.descriptor == &set_color_mode_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_color_mode_request__pack
                     (const SetColorModeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_color_mode_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_color_mode_request__pack_to_buffer
                     (const SetColorModeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_color_mode_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetColorModeRequest *
       set_color_mode_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetColorModeRequest *)
     protobuf_c_message_unpack (&set_color_mode_request__descriptor,
                                allocator, len, data);
}
void   set_color_mode_request__free_unpacked
                     (SetColorModeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_color_mode_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_static_color_request__init
                     (SetStaticColorRequest         *message)
{
  static const SetStaticColorRequest init_value = SET_STATIC_COLOR_REQUEST__INIT;
  *message = init_value;
}
size_t set_static_color_request__get_packed_size
                     (const SetStaticColorRequest *message)
{
  assert(message->base.descriptor == &set_static_color_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_static_color_request__pack
                     (const SetStaticColorRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_static_color_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_static_color_request__pack_to_buffer
                     (const SetStaticColorRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_static_color_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetStaticColorRequest *
       set_static_color_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetStaticColorRequest *)
     protobuf_c_message_unpack (&set_static_color_request__descriptor,
                                allocator, len, data);
}
void   set_static_color_request__free_unpacked
                     (SetStaticColorRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_static_color_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rtcrequest__init
                     (RTCRequest         *message)
{
  static const RTCRequest init_value = RTCREQUEST__INIT;
  *message = init_value;
}
size_t rtcrequest__get_packed_size
                     (const RTCRequest *message)
{
  assert(message->base.descriptor == &rtcrequest__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rtcrequest__pack
                     (const RTCRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rtcrequest__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rtcrequest__pack_to_buffer
                     (const RTCRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rtcrequest__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RTCRequest *
       rtcrequest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RTCRequest *)
     protobuf_c_message_unpack (&rtcrequest__descriptor,
                                allocator, len, data);
}
void   rtcrequest__free_unpacked
                     (RTCRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rtcrequest__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_time_point_request__time__init
                     (ListTimePointRequest__Time         *message)
{
  static const ListTimePointRequest__Time init_value = LIST_TIME_POINT_REQUEST__TIME__INIT;
  *message = init_value;
}
void   list_time_point_request__init
                     (ListTimePointRequest         *message)
{
  static const ListTimePointRequest init_value = LIST_TIME_POINT_REQUEST__INIT;
  *message = init_value;
}
size_t list_time_point_request__get_packed_size
                     (const ListTimePointRequest *message)
{
  assert(message->base.descriptor == &list_time_point_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_time_point_request__pack
                     (const ListTimePointRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_time_point_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_time_point_request__pack_to_buffer
                     (const ListTimePointRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_time_point_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListTimePointRequest *
       list_time_point_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListTimePointRequest *)
     protobuf_c_message_unpack (&list_time_point_request__descriptor,
                                allocator, len, data);
}
void   list_time_point_request__free_unpacked
                     (ListTimePointRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_time_point_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lighting_schedule_request__init
                     (LightingScheduleRequest         *message)
{
  static const LightingScheduleRequest init_value = LIGHTING_SCHEDULE_REQUEST__INIT;
  *message = init_value;
}
size_t lighting_schedule_request__get_packed_size
                     (const LightingScheduleRequest *message)
{
  assert(message->base.descriptor == &lighting_schedule_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lighting_schedule_request__pack
                     (const LightingScheduleRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lighting_schedule_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lighting_schedule_request__pack_to_buffer
                     (const LightingScheduleRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lighting_schedule_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LightingScheduleRequest *
       lighting_schedule_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LightingScheduleRequest *)
     protobuf_c_message_unpack (&lighting_schedule_request__descriptor,
                                allocator, len, data);
}
void   lighting_schedule_request__free_unpacked
                     (LightingScheduleRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lighting_schedule_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_scene_request__init
                     (SetSceneRequest         *message)
{
  static const SetSceneRequest init_value = SET_SCENE_REQUEST__INIT;
  *message = init_value;
}
size_t set_scene_request__get_packed_size
                     (const SetSceneRequest *message)
{
  assert(message->base.descriptor == &set_scene_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_scene_request__pack
                     (const SetSceneRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_scene_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_scene_request__pack_to_buffer
                     (const SetSceneRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_scene_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetSceneRequest *
       set_scene_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetSceneRequest *)
     protobuf_c_message_unpack (&set_scene_request__descriptor,
                                allocator, len, data);
}
void   set_scene_request__free_unpacked
                     (SetSceneRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_scene_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_scene_response__init
                     (GetSceneResponse         *message)
{
  static const GetSceneResponse init_value = GET_SCENE_RESPONSE__INIT;
  *message = init_value;
}
size_t get_scene_response__get_packed_size
                     (const GetSceneResponse *message)
{
  assert(message->base.descriptor == &get_scene_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_scene_response__pack
                     (const GetSceneResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_scene_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_scene_response__pack_to_buffer
                     (const GetSceneResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_scene_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetSceneResponse *
       get_scene_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetSceneResponse *)
     protobuf_c_message_unpack (&get_scene_response__descriptor,
                                allocator, len, data);
}
void   get_scene_response__free_unpacked
                     (GetSceneResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_scene_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   effect__init
                     (Effect         *message)
{
  static const Effect init_value = EFFECT__INIT;
  *message = init_value;
}
size_t effect__get_packed_size
                     (const Effect *message)
{
  assert(message->base.descriptor == &effect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t effect__pack
                     (const Effect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &effect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t effect__pack_to_buffer
                     (const Effect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &effect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Effect *
       effect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Effect *)
     protobuf_c_message_unpack (&effect__descriptor,
                                allocator, len, data);
}
void   effect__free_unpacked
                     (Effect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &effect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   upgrade_firmware_request__init
                     (UpgradeFirmwareRequest         *message)
{
  static const UpgradeFirmwareRequest init_value = UPGRADE_FIRMWARE_REQUEST__INIT;
  *message = init_value;
}
size_t upgrade_firmware_request__get_packed_size
                     (const UpgradeFirmwareRequest *message)
{
  assert(message->base.descriptor == &upgrade_firmware_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t upgrade_firmware_request__pack
                     (const UpgradeFirmwareRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &upgrade_firmware_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t upgrade_firmware_request__pack_to_buffer
                     (const UpgradeFirmwareRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &upgrade_firmware_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpgradeFirmwareRequest *
       upgrade_firmware_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpgradeFirmwareRequest *)
     protobuf_c_message_unpack (&upgrade_firmware_request__descriptor,
                                allocator, len, data);
}
void   upgrade_firmware_request__free_unpacked
                     (UpgradeFirmwareRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &upgrade_firmware_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   upgrade_firmware_response__init
                     (UpgradeFirmwareResponse         *message)
{
  static const UpgradeFirmwareResponse init_value = UPGRADE_FIRMWARE_RESPONSE__INIT;
  *message = init_value;
}
size_t upgrade_firmware_response__get_packed_size
                     (const UpgradeFirmwareResponse *message)
{
  assert(message->base.descriptor == &upgrade_firmware_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t upgrade_firmware_response__pack
                     (const UpgradeFirmwareResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &upgrade_firmware_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t upgrade_firmware_response__pack_to_buffer
                     (const UpgradeFirmwareResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &upgrade_firmware_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpgradeFirmwareResponse *
       upgrade_firmware_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpgradeFirmwareResponse *)
     protobuf_c_message_unpack (&upgrade_firmware_response__descriptor,
                                allocator, len, data);
}
void   upgrade_firmware_response__free_unpacked
                     (UpgradeFirmwareResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &upgrade_firmware_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   time_stamp__init
                     (TimeStamp         *message)
{
  static const TimeStamp init_value = TIME_STAMP__INIT;
  *message = init_value;
}
size_t time_stamp__get_packed_size
                     (const TimeStamp *message)
{
  assert(message->base.descriptor == &time_stamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_stamp__pack
                     (const TimeStamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_stamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_stamp__pack_to_buffer
                     (const TimeStamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_stamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimeStamp *
       time_stamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimeStamp *)
     protobuf_c_message_unpack (&time_stamp__descriptor,
                                allocator, len, data);
}
void   time_stamp__free_unpacked
                     (TimeStamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_stamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define device_information_request__field_descriptors NULL
#define device_information_request__field_indices_by_name NULL
#define device_information_request__number_ranges NULL
const ProtobufCMessageDescriptor device_information_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceInformationRequest",
  "DeviceInformationRequest",
  "DeviceInformationRequest",
  "",
  sizeof(DeviceInformationRequest),
  0,
  device_information_request__field_descriptors,
  device_information_request__field_indices_by_name,
  0,  device_information_request__number_ranges,
  (ProtobufCMessageInit) device_information_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_information_response__field_descriptors[5] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DeviceInformationResponse, mode),
    &mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_timestamps",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceInformationResponse, current_timestamps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformationResponse, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformationResponse, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformationResponse, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_information_response__field_indices_by_name[] = {
  1,   /* field[1] = current_timestamps */
  3,   /* field[3] = id */
  0,   /* field[0] = mode */
  2,   /* field[2] = name */
  4,   /* field[4] = version */
};
static const ProtobufCIntRange device_information_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor device_information_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceInformationResponse",
  "DeviceInformationResponse",
  "DeviceInformationResponse",
  "",
  sizeof(DeviceInformationResponse),
  5,
  device_information_response__field_descriptors,
  device_information_response__field_indices_by_name,
  1,  device_information_response__number_ranges,
  (ProtobufCMessageInit) device_information_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_color_mode_request__field_descriptors[1] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SetColorModeRequest, mode),
    &mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_color_mode_request__field_indices_by_name[] = {
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange set_color_mode_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor set_color_mode_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetColorModeRequest",
  "SetColorModeRequest",
  "SetColorModeRequest",
  "",
  sizeof(SetColorModeRequest),
  1,
  set_color_mode_request__field_descriptors,
  set_color_mode_request__field_indices_by_name,
  1,  set_color_mode_request__number_ranges,
  (ProtobufCMessageInit) set_color_mode_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_static_color_request__field_descriptors[7] =
{
  {
    "white",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetStaticColorRequest, white),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warm_white",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetStaticColorRequest, warm_white),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "red",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetStaticColorRequest, red),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "green",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetStaticColorRequest, green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetStaticColorRequest, blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "royal_blue",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetStaticColorRequest, royal_blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ultra_violet",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SetStaticColorRequest, ultra_violet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_static_color_request__field_indices_by_name[] = {
  4,   /* field[4] = blue */
  3,   /* field[3] = green */
  2,   /* field[2] = red */
  5,   /* field[5] = royal_blue */
  6,   /* field[6] = ultra_violet */
  1,   /* field[1] = warm_white */
  0,   /* field[0] = white */
};
static const ProtobufCIntRange set_static_color_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor set_static_color_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetStaticColorRequest",
  "SetStaticColorRequest",
  "SetStaticColorRequest",
  "",
  sizeof(SetStaticColorRequest),
  7,
  set_static_color_request__field_descriptors,
  set_static_color_request__field_indices_by_name,
  1,  set_static_color_request__number_ranges,
  (ProtobufCMessageInit) set_static_color_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rtcrequest__field_descriptors[1] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RTCRequest, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rtcrequest__field_indices_by_name[] = {
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange rtcrequest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rtcrequest__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RTCRequest",
  "RTCRequest",
  "RTCRequest",
  "",
  sizeof(RTCRequest),
  1,
  rtcrequest__field_descriptors,
  rtcrequest__field_indices_by_name,
  1,  rtcrequest__number_ranges,
  (ProtobufCMessageInit) rtcrequest__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_time_point_request__time__field_descriptors[2] =
{
  {
    "hh",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ListTimePointRequest__Time, hh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ListTimePointRequest__Time, mm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_time_point_request__time__field_indices_by_name[] = {
  0,   /* field[0] = hh */
  1,   /* field[1] = mm */
};
static const ProtobufCIntRange list_time_point_request__time__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor list_time_point_request__time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListTimePointRequest.Time",
  "Time",
  "ListTimePointRequest__Time",
  "",
  sizeof(ListTimePointRequest__Time),
  2,
  list_time_point_request__time__field_descriptors,
  list_time_point_request__time__field_indices_by_name,
  1,  list_time_point_request__time__number_ranges,
  (ProtobufCMessageInit) list_time_point_request__time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_time_point_request__field_descriptors[1] =
{
  {
    "times",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ListTimePointRequest, n_times),
    offsetof(ListTimePointRequest, times),
    &list_time_point_request__time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_time_point_request__field_indices_by_name[] = {
  0,   /* field[0] = times */
};
static const ProtobufCIntRange list_time_point_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor list_time_point_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListTimePointRequest",
  "ListTimePointRequest",
  "ListTimePointRequest",
  "",
  sizeof(ListTimePointRequest),
  1,
  list_time_point_request__field_descriptors,
  list_time_point_request__field_indices_by_name,
  1,  list_time_point_request__number_ranges,
  (ProtobufCMessageInit) list_time_point_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lighting_schedule_request__field_descriptors[9] =
{
  {
    "hh",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LightingScheduleRequest, hh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LightingScheduleRequest, mm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "white",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LightingScheduleRequest, white),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warm_white",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LightingScheduleRequest, warm_white),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "red",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LightingScheduleRequest, red),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "green",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LightingScheduleRequest, green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LightingScheduleRequest, blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "royal_blue",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LightingScheduleRequest, royal_blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ultra_violet",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LightingScheduleRequest, ultra_violet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lighting_schedule_request__field_indices_by_name[] = {
  6,   /* field[6] = blue */
  5,   /* field[5] = green */
  0,   /* field[0] = hh */
  1,   /* field[1] = mm */
  4,   /* field[4] = red */
  7,   /* field[7] = royal_blue */
  8,   /* field[8] = ultra_violet */
  3,   /* field[3] = warm_white */
  2,   /* field[2] = white */
};
static const ProtobufCIntRange lighting_schedule_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor lighting_schedule_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LightingScheduleRequest",
  "LightingScheduleRequest",
  "LightingScheduleRequest",
  "",
  sizeof(LightingScheduleRequest),
  9,
  lighting_schedule_request__field_descriptors,
  lighting_schedule_request__field_indices_by_name,
  1,  lighting_schedule_request__number_ranges,
  (ProtobufCMessageInit) lighting_schedule_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_scene_request__field_descriptors[1] =
{
  {
    "scene",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SetSceneRequest, scene),
    &scene__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_scene_request__field_indices_by_name[] = {
  0,   /* field[0] = scene */
};
static const ProtobufCIntRange set_scene_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor set_scene_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetSceneRequest",
  "SetSceneRequest",
  "SetSceneRequest",
  "",
  sizeof(SetSceneRequest),
  1,
  set_scene_request__field_descriptors,
  set_scene_request__field_indices_by_name,
  1,  set_scene_request__number_ranges,
  (ProtobufCMessageInit) set_scene_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_scene_response__field_descriptors[1] =
{
  {
    "scene",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GetSceneResponse, scene),
    &scene__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_scene_response__field_indices_by_name[] = {
  0,   /* field[0] = scene */
};
static const ProtobufCIntRange get_scene_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_scene_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetSceneResponse",
  "GetSceneResponse",
  "GetSceneResponse",
  "",
  sizeof(GetSceneResponse),
  1,
  get_scene_response__field_descriptors,
  get_scene_response__field_indices_by_name,
  1,  get_scene_response__number_ranges,
  (ProtobufCMessageInit) get_scene_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor effect__field_descriptors[2] =
{
  {
    "duration",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Effect, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamps",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Effect, n_timestamps),
    offsetof(Effect, timestamps),
    &time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned effect__field_indices_by_name[] = {
  0,   /* field[0] = duration */
  1,   /* field[1] = timestamps */
};
static const ProtobufCIntRange effect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor effect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Effect",
  "Effect",
  "Effect",
  "",
  sizeof(Effect),
  2,
  effect__field_descriptors,
  effect__field_indices_by_name,
  1,  effect__number_ranges,
  (ProtobufCMessageInit) effect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define upgrade_firmware_request__field_descriptors NULL
#define upgrade_firmware_request__field_indices_by_name NULL
#define upgrade_firmware_request__number_ranges NULL
const ProtobufCMessageDescriptor upgrade_firmware_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UpgradeFirmwareRequest",
  "UpgradeFirmwareRequest",
  "UpgradeFirmwareRequest",
  "",
  sizeof(UpgradeFirmwareRequest),
  0,
  upgrade_firmware_request__field_descriptors,
  upgrade_firmware_request__field_indices_by_name,
  0,  upgrade_firmware_request__number_ranges,
  (ProtobufCMessageInit) upgrade_firmware_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor upgrade_firmware_response__field_descriptors[2] =
{
  {
    "is_latest_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(UpgradeFirmwareResponse, is_latest_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UpgradeFirmwareResponse, current_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned upgrade_firmware_response__field_indices_by_name[] = {
  1,   /* field[1] = current_version */
  0,   /* field[0] = is_latest_version */
};
static const ProtobufCIntRange upgrade_firmware_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor upgrade_firmware_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UpgradeFirmwareResponse",
  "UpgradeFirmwareResponse",
  "UpgradeFirmwareResponse",
  "",
  sizeof(UpgradeFirmwareResponse),
  2,
  upgrade_firmware_response__field_descriptors,
  upgrade_firmware_response__field_indices_by_name,
  1,  upgrade_firmware_response__number_ranges,
  (ProtobufCMessageInit) upgrade_firmware_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor time_stamp__field_descriptors[8] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "white",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, white),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warm_white",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, warm_white),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "red",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, red),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "green",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "royal_blue",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, royal_blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ultra_violet",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, ultra_violet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_stamp__field_indices_by_name[] = {
  5,   /* field[5] = blue */
  4,   /* field[4] = green */
  3,   /* field[3] = red */
  6,   /* field[6] = royal_blue */
  0,   /* field[0] = seconds */
  7,   /* field[7] = ultra_violet */
  2,   /* field[2] = warm_white */
  1,   /* field[1] = white */
};
static const ProtobufCIntRange time_stamp__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor time_stamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimeStamp",
  "TimeStamp",
  "TimeStamp",
  "",
  sizeof(TimeStamp),
  8,
  time_stamp__field_descriptors,
  time_stamp__field_indices_by_name,
  2,  time_stamp__number_ranges,
  (ProtobufCMessageInit) time_stamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue scene__enum_values_by_number[1] =
{
  { "SCENE_UNSPECIFIED", "SCENE__SCENE_UNSPECIFIED", 0 },
};
static const ProtobufCIntRange scene__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex scene__enum_values_by_name[1] =
{
  { "SCENE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor scene__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Scene",
  "Scene",
  "Scene",
  "",
  1,
  scene__enum_values_by_number,
  1,
  scene__enum_values_by_name,
  1,
  scene__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue command_code__enum_values_by_number[4] =
{
  { "COMMAND_CODE_UNSPECIFIED", "COMMAND_CODE__COMMAND_CODE_UNSPECIFIED", 0 },
  { "COMMAND_CODE_GET_PROPERTIES", "COMMAND_CODE__COMMAND_CODE_GET_PROPERTIES", 1 },
  { "COMMAND_CODE_SET_LIGHTING", "COMMAND_CODE__COMMAND_CODE_SET_LIGHTING", 5 },
  { "COMMAND_CODE_UPGRADE_FIRMWARE", "COMMAND_CODE__COMMAND_CODE_UPGRADE_FIRMWARE", 6 },
};
static const ProtobufCIntRange command_code__value_ranges[] = {
{0, 0},{5, 2},{0, 4}
};
static const ProtobufCEnumValueIndex command_code__enum_values_by_name[4] =
{
  { "COMMAND_CODE_GET_PROPERTIES", 1 },
  { "COMMAND_CODE_SET_LIGHTING", 2 },
  { "COMMAND_CODE_UNSPECIFIED", 0 },
  { "COMMAND_CODE_UPGRADE_FIRMWARE", 3 },
};
const ProtobufCEnumDescriptor command_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CommandCode",
  "CommandCode",
  "CommandCode",
  "",
  4,
  command_code__enum_values_by_number,
  4,
  command_code__enum_values_by_name,
  2,
  command_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue mode__enum_values_by_number[3] =
{
  { "MODE_UNSPECIFIED", "MODE__MODE_UNSPECIFIED", 0 },
  { "MODE_MANUAL", "MODE__MODE_MANUAL", 1 },
  { "MODE_SCHEDULE", "MODE__MODE_SCHEDULE", 2 },
};
static const ProtobufCIntRange mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex mode__enum_values_by_name[3] =
{
  { "MODE_MANUAL", 1 },
  { "MODE_SCHEDULE", 2 },
  { "MODE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Mode",
  "Mode",
  "Mode",
  "",
  3,
  mode__enum_values_by_number,
  3,
  mode__enum_values_by_name,
  1,
  mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
