/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/message.proto */

#ifndef PROTOBUF_C_proto_2fmessage_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct DeviceInformationRequest DeviceInformationRequest;
typedef struct DeviceInformationResponse DeviceInformationResponse;
typedef struct LightingScheduleRequest LightingScheduleRequest;
typedef struct SetSceneRequest SetSceneRequest;
typedef struct GetSceneResponse GetSceneResponse;
typedef struct Effect Effect;
typedef struct UpgradeFirmwareRequest UpgradeFirmwareRequest;
typedef struct UpgradeFirmwareResponse UpgradeFirmwareResponse;
typedef struct TimeStamp TimeStamp;


/* --- enums --- */

typedef enum _Scene {
  SCENE__SCENE_UNSPECIFIED = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SCENE)
} Scene;
typedef enum _CommandCode {
  COMMAND_CODE__COMMAND_CODE_UNSPECIFIED = 0,
  COMMAND_CODE__COMMAND_CODE_GET_PROPERTIES = 1,
  /*
   * prepend
   */
  COMMAND_CODE__COMMAND_CODE_SET_LIGHTING = 5,
  COMMAND_CODE__COMMAND_CODE_UPGRADE_FIRMWARE = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMMAND_CODE)
} CommandCode;
/*
 * Mode specifies the mode of the lighting
 */
typedef enum _Mode {
  MODE__MODE_UNSPECIFIED = 0,
  /*
   * Manual mode
   * show static lighting
   */
  MODE__MODE_MANUAL = 1,
  /*
   * Schedule mode
   * show lighting based on schedule time configured
   */
  MODE__MODE_SCHEDULE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MODE)
} Mode;
/*
 * LED specifies the LED
 */
typedef enum _LED {
  LED__LED_UNSPECIFIED = 0,
  LED__LED_WHITE = 1,
  LED__LED_WARM_WHITE = 2,
  LED__LED_RED = 3,
  LED__LED_GREEN = 4,
  LED__LED_BLUE = 5,
  LED__LED_ROYAL_BLUE = 6,
  LED__LED_ULTRA_VIOLET = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LED)
} LED;

/* --- messages --- */

struct  DeviceInformationRequest
{
  ProtobufCMessage base;
};
#define DEVICE_INFORMATION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&device_information_request__descriptor) \
 }


struct  DeviceInformationResponse
{
  ProtobufCMessage base;
  Mode mode;
  uint32_t current_timestamps;
  char *name;
  char *id;
  char *version;
};
#define DEVICE_INFORMATION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&device_information_response__descriptor) \
, MODE__MODE_UNSPECIFIED, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * LightingScheduleRequest is the data that will be sent
 * to the device
 * which is sent one by one (time point) to the device
 */
struct  LightingScheduleRequest
{
  ProtobufCMessage base;
  uint32_t hh;
  uint32_t mm;
  uint32_t white;
  uint32_t warm_white;
  uint32_t red;
  uint32_t green;
  uint32_t blue;
  uint32_t royal_blue;
  uint32_t ultra_violet;
};
#define LIGHTING_SCHEDULE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lighting_schedule_request__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  SetSceneRequest
{
  ProtobufCMessage base;
  Scene scene;
};
#define SET_SCENE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&set_scene_request__descriptor) \
, SCENE__SCENE_UNSPECIFIED }


struct  GetSceneResponse
{
  ProtobufCMessage base;
  Scene scene;
};
#define GET_SCENE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&get_scene_response__descriptor) \
, SCENE__SCENE_UNSPECIFIED }


/*
 * Effect store a list of TimeStamp
 * and how long the effect should last
 */
struct  Effect
{
  ProtobufCMessage base;
  uint32_t duration;
  size_t n_timestamps;
  TimeStamp **timestamps;
};
#define EFFECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&effect__descriptor) \
, 0, 0,NULL }


struct  UpgradeFirmwareRequest
{
  ProtobufCMessage base;
};
#define UPGRADE_FIRMWARE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&upgrade_firmware_request__descriptor) \
 }


struct  UpgradeFirmwareResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean is_latest_version;
  char *current_version;
};
#define UPGRADE_FIRMWARE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&upgrade_firmware_response__descriptor) \
, 0, (char *)protobuf_c_empty_string }


struct  TimeStamp
{
  ProtobufCMessage base;
  uint32_t seconds;
  uint32_t white;
  uint32_t warm_white;
  uint32_t red;
  uint32_t green;
  uint32_t blue;
  uint32_t royal_blue;
  uint32_t ultra_violet;
};
#define TIME_STAMP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&time_stamp__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0 }


/* DeviceInformationRequest methods */
void   device_information_request__init
                     (DeviceInformationRequest         *message);
size_t device_information_request__get_packed_size
                     (const DeviceInformationRequest   *message);
size_t device_information_request__pack
                     (const DeviceInformationRequest   *message,
                      uint8_t             *out);
size_t device_information_request__pack_to_buffer
                     (const DeviceInformationRequest   *message,
                      ProtobufCBuffer     *buffer);
DeviceInformationRequest *
       device_information_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   device_information_request__free_unpacked
                     (DeviceInformationRequest *message,
                      ProtobufCAllocator *allocator);
/* DeviceInformationResponse methods */
void   device_information_response__init
                     (DeviceInformationResponse         *message);
size_t device_information_response__get_packed_size
                     (const DeviceInformationResponse   *message);
size_t device_information_response__pack
                     (const DeviceInformationResponse   *message,
                      uint8_t             *out);
size_t device_information_response__pack_to_buffer
                     (const DeviceInformationResponse   *message,
                      ProtobufCBuffer     *buffer);
DeviceInformationResponse *
       device_information_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   device_information_response__free_unpacked
                     (DeviceInformationResponse *message,
                      ProtobufCAllocator *allocator);
/* LightingScheduleRequest methods */
void   lighting_schedule_request__init
                     (LightingScheduleRequest         *message);
size_t lighting_schedule_request__get_packed_size
                     (const LightingScheduleRequest   *message);
size_t lighting_schedule_request__pack
                     (const LightingScheduleRequest   *message,
                      uint8_t             *out);
size_t lighting_schedule_request__pack_to_buffer
                     (const LightingScheduleRequest   *message,
                      ProtobufCBuffer     *buffer);
LightingScheduleRequest *
       lighting_schedule_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lighting_schedule_request__free_unpacked
                     (LightingScheduleRequest *message,
                      ProtobufCAllocator *allocator);
/* SetSceneRequest methods */
void   set_scene_request__init
                     (SetSceneRequest         *message);
size_t set_scene_request__get_packed_size
                     (const SetSceneRequest   *message);
size_t set_scene_request__pack
                     (const SetSceneRequest   *message,
                      uint8_t             *out);
size_t set_scene_request__pack_to_buffer
                     (const SetSceneRequest   *message,
                      ProtobufCBuffer     *buffer);
SetSceneRequest *
       set_scene_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   set_scene_request__free_unpacked
                     (SetSceneRequest *message,
                      ProtobufCAllocator *allocator);
/* GetSceneResponse methods */
void   get_scene_response__init
                     (GetSceneResponse         *message);
size_t get_scene_response__get_packed_size
                     (const GetSceneResponse   *message);
size_t get_scene_response__pack
                     (const GetSceneResponse   *message,
                      uint8_t             *out);
size_t get_scene_response__pack_to_buffer
                     (const GetSceneResponse   *message,
                      ProtobufCBuffer     *buffer);
GetSceneResponse *
       get_scene_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   get_scene_response__free_unpacked
                     (GetSceneResponse *message,
                      ProtobufCAllocator *allocator);
/* Effect methods */
void   effect__init
                     (Effect         *message);
size_t effect__get_packed_size
                     (const Effect   *message);
size_t effect__pack
                     (const Effect   *message,
                      uint8_t             *out);
size_t effect__pack_to_buffer
                     (const Effect   *message,
                      ProtobufCBuffer     *buffer);
Effect *
       effect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   effect__free_unpacked
                     (Effect *message,
                      ProtobufCAllocator *allocator);
/* UpgradeFirmwareRequest methods */
void   upgrade_firmware_request__init
                     (UpgradeFirmwareRequest         *message);
size_t upgrade_firmware_request__get_packed_size
                     (const UpgradeFirmwareRequest   *message);
size_t upgrade_firmware_request__pack
                     (const UpgradeFirmwareRequest   *message,
                      uint8_t             *out);
size_t upgrade_firmware_request__pack_to_buffer
                     (const UpgradeFirmwareRequest   *message,
                      ProtobufCBuffer     *buffer);
UpgradeFirmwareRequest *
       upgrade_firmware_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   upgrade_firmware_request__free_unpacked
                     (UpgradeFirmwareRequest *message,
                      ProtobufCAllocator *allocator);
/* UpgradeFirmwareResponse methods */
void   upgrade_firmware_response__init
                     (UpgradeFirmwareResponse         *message);
size_t upgrade_firmware_response__get_packed_size
                     (const UpgradeFirmwareResponse   *message);
size_t upgrade_firmware_response__pack
                     (const UpgradeFirmwareResponse   *message,
                      uint8_t             *out);
size_t upgrade_firmware_response__pack_to_buffer
                     (const UpgradeFirmwareResponse   *message,
                      ProtobufCBuffer     *buffer);
UpgradeFirmwareResponse *
       upgrade_firmware_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   upgrade_firmware_response__free_unpacked
                     (UpgradeFirmwareResponse *message,
                      ProtobufCAllocator *allocator);
/* TimeStamp methods */
void   time_stamp__init
                     (TimeStamp         *message);
size_t time_stamp__get_packed_size
                     (const TimeStamp   *message);
size_t time_stamp__pack
                     (const TimeStamp   *message,
                      uint8_t             *out);
size_t time_stamp__pack_to_buffer
                     (const TimeStamp   *message,
                      ProtobufCBuffer     *buffer);
TimeStamp *
       time_stamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   time_stamp__free_unpacked
                     (TimeStamp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DeviceInformationRequest_Closure)
                 (const DeviceInformationRequest *message,
                  void *closure_data);
typedef void (*DeviceInformationResponse_Closure)
                 (const DeviceInformationResponse *message,
                  void *closure_data);
typedef void (*LightingScheduleRequest_Closure)
                 (const LightingScheduleRequest *message,
                  void *closure_data);
typedef void (*SetSceneRequest_Closure)
                 (const SetSceneRequest *message,
                  void *closure_data);
typedef void (*GetSceneResponse_Closure)
                 (const GetSceneResponse *message,
                  void *closure_data);
typedef void (*Effect_Closure)
                 (const Effect *message,
                  void *closure_data);
typedef void (*UpgradeFirmwareRequest_Closure)
                 (const UpgradeFirmwareRequest *message,
                  void *closure_data);
typedef void (*UpgradeFirmwareResponse_Closure)
                 (const UpgradeFirmwareResponse *message,
                  void *closure_data);
typedef void (*TimeStamp_Closure)
                 (const TimeStamp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    scene__descriptor;
extern const ProtobufCEnumDescriptor    command_code__descriptor;
extern const ProtobufCEnumDescriptor    mode__descriptor;
extern const ProtobufCEnumDescriptor    led__descriptor;
extern const ProtobufCMessageDescriptor device_information_request__descriptor;
extern const ProtobufCMessageDescriptor device_information_response__descriptor;
extern const ProtobufCMessageDescriptor lighting_schedule_request__descriptor;
extern const ProtobufCMessageDescriptor set_scene_request__descriptor;
extern const ProtobufCMessageDescriptor get_scene_response__descriptor;
extern const ProtobufCMessageDescriptor effect__descriptor;
extern const ProtobufCMessageDescriptor upgrade_firmware_request__descriptor;
extern const ProtobufCMessageDescriptor upgrade_firmware_response__descriptor;
extern const ProtobufCMessageDescriptor time_stamp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fmessage_2eproto__INCLUDED */
