/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/message.pb-c.h"
void   command_result__init
                     (CommandResult         *message)
{
  static const CommandResult init_value = COMMAND_RESULT__INIT;
  *message = init_value;
}
size_t command_result__get_packed_size
                     (const CommandResult *message)
{
  assert(message->base.descriptor == &command_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t command_result__pack
                     (const CommandResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &command_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t command_result__pack_to_buffer
                     (const CommandResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &command_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CommandResult *
       command_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CommandResult *)
     protobuf_c_message_unpack (&command_result__descriptor,
                                allocator, len, data);
}
void   command_result__free_unpacked
                     (CommandResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &command_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lighting__init
                     (Lighting         *message)
{
  static const Lighting init_value = LIGHTING__INIT;
  *message = init_value;
}
size_t lighting__get_packed_size
                     (const Lighting *message)
{
  assert(message->base.descriptor == &lighting__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lighting__pack
                     (const Lighting *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lighting__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lighting__pack_to_buffer
                     (const Lighting *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lighting__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lighting *
       lighting__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lighting *)
     protobuf_c_message_unpack (&lighting__descriptor,
                                allocator, len, data);
}
void   lighting__free_unpacked
                     (Lighting *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lighting__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   time_points__init
                     (TimePoints         *message)
{
  static const TimePoints init_value = TIME_POINTS__INIT;
  *message = init_value;
}
size_t time_points__get_packed_size
                     (const TimePoints *message)
{
  assert(message->base.descriptor == &time_points__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_points__pack
                     (const TimePoints *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_points__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_points__pack_to_buffer
                     (const TimePoints *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_points__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimePoints *
       time_points__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimePoints *)
     protobuf_c_message_unpack (&time_points__descriptor,
                                allocator, len, data);
}
void   time_points__free_unpacked
                     (TimePoints *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_points__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   effect__init
                     (Effect         *message)
{
  static const Effect init_value = EFFECT__INIT;
  *message = init_value;
}
size_t effect__get_packed_size
                     (const Effect *message)
{
  assert(message->base.descriptor == &effect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t effect__pack
                     (const Effect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &effect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t effect__pack_to_buffer
                     (const Effect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &effect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Effect *
       effect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Effect *)
     protobuf_c_message_unpack (&effect__descriptor,
                                allocator, len, data);
}
void   effect__free_unpacked
                     (Effect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &effect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   time_point__init
                     (TimePoint         *message)
{
  static const TimePoint init_value = TIME_POINT__INIT;
  *message = init_value;
}
size_t time_point__get_packed_size
                     (const TimePoint *message)
{
  assert(message->base.descriptor == &time_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_point__pack
                     (const TimePoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_point__pack_to_buffer
                     (const TimePoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimePoint *
       time_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimePoint *)
     protobuf_c_message_unpack (&time_point__descriptor,
                                allocator, len, data);
}
void   time_point__free_unpacked
                     (TimePoint *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   brightness__init
                     (Brightness         *message)
{
  static const Brightness init_value = BRIGHTNESS__INIT;
  *message = init_value;
}
size_t brightness__get_packed_size
                     (const Brightness *message)
{
  assert(message->base.descriptor == &brightness__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t brightness__pack
                     (const Brightness *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &brightness__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t brightness__pack_to_buffer
                     (const Brightness *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &brightness__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Brightness *
       brightness__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Brightness *)
     protobuf_c_message_unpack (&brightness__descriptor,
                                allocator, len, data);
}
void   brightness__free_unpacked
                     (Brightness *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &brightness__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   time_stamp__init
                     (TimeStamp         *message)
{
  static const TimeStamp init_value = TIME_STAMP__INIT;
  *message = init_value;
}
size_t time_stamp__get_packed_size
                     (const TimeStamp *message)
{
  assert(message->base.descriptor == &time_stamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_stamp__pack
                     (const TimeStamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_stamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_stamp__pack_to_buffer
                     (const TimeStamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_stamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimeStamp *
       time_stamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimeStamp *)
     protobuf_c_message_unpack (&time_stamp__descriptor,
                                allocator, len, data);
}
void   time_stamp__free_unpacked
                     (TimeStamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_stamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor command_result__field_descriptors[3] =
{
  {
    "ok",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(CommandResult, ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CommandResult, error_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CommandResult, error_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned command_result__field_indices_by_name[] = {
  1,   /* field[1] = error_code */
  2,   /* field[2] = error_message */
  0,   /* field[0] = ok */
};
static const ProtobufCIntRange command_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor command_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CommandResult",
  "CommandResult",
  "CommandResult",
  "",
  sizeof(CommandResult),
  3,
  command_result__field_descriptors,
  command_result__field_indices_by_name,
  1,  command_result__number_ranges,
  (ProtobufCMessageInit) command_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lighting__field_descriptors[4] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Lighting, mode),
    &mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schedule",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lighting, data_case),
    offsetof(Lighting, schedule),
    &time_points__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "effect",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lighting, data_case),
    offsetof(Lighting, effect),
    &effect__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rgb",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Lighting, data_case),
    offsetof(Lighting, rgb),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lighting__field_indices_by_name[] = {
  2,   /* field[2] = effect */
  0,   /* field[0] = mode */
  3,   /* field[3] = rgb */
  1,   /* field[1] = schedule */
};
static const ProtobufCIntRange lighting__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor lighting__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lighting",
  "Lighting",
  "Lighting",
  "",
  sizeof(Lighting),
  4,
  lighting__field_descriptors,
  lighting__field_indices_by_name,
  1,  lighting__number_ranges,
  (ProtobufCMessageInit) lighting__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor time_points__field_descriptors[1] =
{
  {
    "points",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TimePoints, n_points),
    offsetof(TimePoints, points),
    &time_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_points__field_indices_by_name[] = {
  0,   /* field[0] = points */
};
static const ProtobufCIntRange time_points__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor time_points__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimePoints",
  "TimePoints",
  "TimePoints",
  "",
  sizeof(TimePoints),
  1,
  time_points__field_descriptors,
  time_points__field_indices_by_name,
  1,  time_points__number_ranges,
  (ProtobufCMessageInit) time_points__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor effect__field_descriptors[2] =
{
  {
    "duration",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Effect, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamps",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Effect, n_timestamps),
    offsetof(Effect, timestamps),
    &time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned effect__field_indices_by_name[] = {
  0,   /* field[0] = duration */
  1,   /* field[1] = timestamps */
};
static const ProtobufCIntRange effect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor effect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Effect",
  "Effect",
  "Effect",
  "",
  sizeof(Effect),
  2,
  effect__field_descriptors,
  effect__field_indices_by_name,
  1,  effect__number_ranges,
  (ProtobufCMessageInit) effect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor time_point__field_descriptors[3] =
{
  {
    "hh",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimePoint, hh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimePoint, mm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brightness",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TimePoint, brightness),
    &brightness__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_point__field_indices_by_name[] = {
  2,   /* field[2] = brightness */
  0,   /* field[0] = hh */
  1,   /* field[1] = mm */
};
static const ProtobufCIntRange time_point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor time_point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimePoint",
  "TimePoint",
  "TimePoint",
  "",
  sizeof(TimePoint),
  3,
  time_point__field_descriptors,
  time_point__field_indices_by_name,
  1,  time_point__number_ranges,
  (ProtobufCMessageInit) time_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor brightness__field_descriptors[7] =
{
  {
    "white",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, white),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warm_white",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, warm_white),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "red",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, red),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "green",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "royal_blue",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, royal_blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ultra_violet",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, ultra_violet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned brightness__field_indices_by_name[] = {
  4,   /* field[4] = blue */
  3,   /* field[3] = green */
  2,   /* field[2] = red */
  5,   /* field[5] = royal_blue */
  6,   /* field[6] = ultra_violet */
  1,   /* field[1] = warm_white */
  0,   /* field[0] = white */
};
static const ProtobufCIntRange brightness__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor brightness__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Brightness",
  "Brightness",
  "Brightness",
  "",
  sizeof(Brightness),
  7,
  brightness__field_descriptors,
  brightness__field_indices_by_name,
  1,  brightness__number_ranges,
  (ProtobufCMessageInit) brightness__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor time_stamp__field_descriptors[2] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brightness",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, brightness),
    &brightness__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_stamp__field_indices_by_name[] = {
  1,   /* field[1] = brightness */
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange time_stamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor time_stamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimeStamp",
  "TimeStamp",
  "TimeStamp",
  "",
  sizeof(TimeStamp),
  2,
  time_stamp__field_descriptors,
  time_stamp__field_indices_by_name,
  1,  time_stamp__number_ranges,
  (ProtobufCMessageInit) time_stamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue command_code__enum_values_by_number[4] =
{
  { "COMMAND_CODE_UNSPECIFIED", "COMMAND_CODE__COMMAND_CODE_UNSPECIFIED", 0 },
  { "COMMAND_GET_PROPERTIES", "COMMAND_CODE__COMMAND_GET_PROPERTIES", 1 },
  { "COMMAND_SET_LIGHTING", "COMMAND_CODE__COMMAND_SET_LIGHTING", 5 },
  { "COMMAND_UPGRADE_FIRMWARE", "COMMAND_CODE__COMMAND_UPGRADE_FIRMWARE", 6 },
};
static const ProtobufCIntRange command_code__value_ranges[] = {
{0, 0},{5, 2},{0, 4}
};
static const ProtobufCEnumValueIndex command_code__enum_values_by_name[4] =
{
  { "COMMAND_CODE_UNSPECIFIED", 0 },
  { "COMMAND_GET_PROPERTIES", 1 },
  { "COMMAND_SET_LIGHTING", 2 },
  { "COMMAND_UPGRADE_FIRMWARE", 3 },
};
const ProtobufCEnumDescriptor command_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CommandCode",
  "CommandCode",
  "CommandCode",
  "",
  4,
  command_code__enum_values_by_number,
  4,
  command_code__enum_values_by_name,
  2,
  command_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue mode__enum_values_by_number[3] =
{
  { "MODE_UNSPECIFIED", "MODE__MODE_UNSPECIFIED", 0 },
  { "MODE_MANUAL", "MODE__MODE_MANUAL", 1 },
  { "MODE_SCHEDULE", "MODE__MODE_SCHEDULE", 2 },
};
static const ProtobufCIntRange mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex mode__enum_values_by_name[3] =
{
  { "MODE_MANUAL", 1 },
  { "MODE_SCHEDULE", 2 },
  { "MODE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Mode",
  "Mode",
  "Mode",
  "",
  3,
  mode__enum_values_by_number,
  3,
  mode__enum_values_by_name,
  1,
  mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue led__enum_values_by_number[8] =
{
  { "LED_UNSPECIFIED", "LED__LED_UNSPECIFIED", 0 },
  { "LED_WHITE", "LED__LED_WHITE", 1 },
  { "LED_WARM_WHITE", "LED__LED_WARM_WHITE", 2 },
  { "LED_RED", "LED__LED_RED", 3 },
  { "LED_GREEN", "LED__LED_GREEN", 4 },
  { "LED_BLUE", "LED__LED_BLUE", 5 },
  { "LED_ROYAL_BLUE", "LED__LED_ROYAL_BLUE", 6 },
  { "LED_ULTRA_VIOLET", "LED__LED_ULTRA_VIOLET", 7 },
};
static const ProtobufCIntRange led__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex led__enum_values_by_name[8] =
{
  { "LED_BLUE", 5 },
  { "LED_GREEN", 4 },
  { "LED_RED", 3 },
  { "LED_ROYAL_BLUE", 6 },
  { "LED_ULTRA_VIOLET", 7 },
  { "LED_UNSPECIFIED", 0 },
  { "LED_WARM_WHITE", 2 },
  { "LED_WHITE", 1 },
};
const ProtobufCEnumDescriptor led__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "LED",
  "LED",
  "LED",
  "",
  8,
  led__enum_values_by_number,
  8,
  led__enum_values_by_name,
  1,
  led__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
