#define DEVICE_INFORMATION_SERVICE_UUID NimBLEUUID("b9657ece-06cd-d4a1-b746-baf222ef4028")
#define COLOR_SERVICE_UUID NimBLEUUID("72b60562-580c-4946-b3b5-8bd8bf8d8c5b")
#define RTC_SERVICE_UUID NimBLEUUID("2f659cc6-7bdc-4c2a-966f-2411706b0b85")

#define CHARACTERISTIC_UUID_DEVICE_NAME NimBLEUUID("")
#define CHARACTERISTIC_UUID_DEVICE_ID NimBLEUUID("")

#define CHARACTERISTIC_UUID_GET_COLOR_MODE NimBLEUUID("")
#define CHARACTERISTIC_UUID_SET_COLOR_MODE NimBLEUUID("")
#define CHARACTERISTIC_UUID_GET_COLOR_TIME_POINTS NimBLEUUID("")
#define CHARACTERISTIC_UUID_ADD_COLOR_TIME_POINT NimBLEUUID("")

#define CHARACTERISTIC_UUID_GET_CURRENT_TIME NimBLEUUID("")
#define CHARACTERISTIC_UUID_SET_CURRENT_TIME NimBLEUUID("")