/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/message.pb-c.h"
void   device_information_request__init
                     (DeviceInformationRequest         *message)
{
  static const DeviceInformationRequest init_value = DEVICE_INFORMATION_REQUEST__INIT;
  *message = init_value;
}
size_t device_information_request__get_packed_size
                     (const DeviceInformationRequest *message)
{
  assert(message->base.descriptor == &device_information_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_information_request__pack
                     (const DeviceInformationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_information_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_information_request__pack_to_buffer
                     (const DeviceInformationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_information_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceInformationRequest *
       device_information_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceInformationRequest *)
     protobuf_c_message_unpack (&device_information_request__descriptor,
                                allocator, len, data);
}
void   device_information_request__free_unpacked
                     (DeviceInformationRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_information_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   device_information_response__init
                     (DeviceInformationResponse         *message)
{
  static const DeviceInformationResponse init_value = DEVICE_INFORMATION_RESPONSE__INIT;
  *message = init_value;
}
size_t device_information_response__get_packed_size
                     (const DeviceInformationResponse *message)
{
  assert(message->base.descriptor == &device_information_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_information_response__pack
                     (const DeviceInformationResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_information_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_information_response__pack_to_buffer
                     (const DeviceInformationResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_information_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceInformationResponse *
       device_information_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceInformationResponse *)
     protobuf_c_message_unpack (&device_information_response__descriptor,
                                allocator, len, data);
}
void   device_information_response__free_unpacked
                     (DeviceInformationResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_information_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lighting_schedule_request__init
                     (LightingScheduleRequest         *message)
{
  static const LightingScheduleRequest init_value = LIGHTING_SCHEDULE_REQUEST__INIT;
  *message = init_value;
}
size_t lighting_schedule_request__get_packed_size
                     (const LightingScheduleRequest *message)
{
  assert(message->base.descriptor == &lighting_schedule_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lighting_schedule_request__pack
                     (const LightingScheduleRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lighting_schedule_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lighting_schedule_request__pack_to_buffer
                     (const LightingScheduleRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lighting_schedule_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LightingScheduleRequest *
       lighting_schedule_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LightingScheduleRequest *)
     protobuf_c_message_unpack (&lighting_schedule_request__descriptor,
                                allocator, len, data);
}
void   lighting_schedule_request__free_unpacked
                     (LightingScheduleRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lighting_schedule_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_scene_request__init
                     (SetSceneRequest         *message)
{
  static const SetSceneRequest init_value = SET_SCENE_REQUEST__INIT;
  *message = init_value;
}
size_t set_scene_request__get_packed_size
                     (const SetSceneRequest *message)
{
  assert(message->base.descriptor == &set_scene_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_scene_request__pack
                     (const SetSceneRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_scene_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_scene_request__pack_to_buffer
                     (const SetSceneRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_scene_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetSceneRequest *
       set_scene_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetSceneRequest *)
     protobuf_c_message_unpack (&set_scene_request__descriptor,
                                allocator, len, data);
}
void   set_scene_request__free_unpacked
                     (SetSceneRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_scene_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_scene_response__init
                     (GetSceneResponse         *message)
{
  static const GetSceneResponse init_value = GET_SCENE_RESPONSE__INIT;
  *message = init_value;
}
size_t get_scene_response__get_packed_size
                     (const GetSceneResponse *message)
{
  assert(message->base.descriptor == &get_scene_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_scene_response__pack
                     (const GetSceneResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_scene_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_scene_response__pack_to_buffer
                     (const GetSceneResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_scene_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetSceneResponse *
       get_scene_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetSceneResponse *)
     protobuf_c_message_unpack (&get_scene_response__descriptor,
                                allocator, len, data);
}
void   get_scene_response__free_unpacked
                     (GetSceneResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_scene_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   effect__init
                     (Effect         *message)
{
  static const Effect init_value = EFFECT__INIT;
  *message = init_value;
}
size_t effect__get_packed_size
                     (const Effect *message)
{
  assert(message->base.descriptor == &effect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t effect__pack
                     (const Effect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &effect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t effect__pack_to_buffer
                     (const Effect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &effect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Effect *
       effect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Effect *)
     protobuf_c_message_unpack (&effect__descriptor,
                                allocator, len, data);
}
void   effect__free_unpacked
                     (Effect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &effect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   upgrade_firmware_request__init
                     (UpgradeFirmwareRequest         *message)
{
  static const UpgradeFirmwareRequest init_value = UPGRADE_FIRMWARE_REQUEST__INIT;
  *message = init_value;
}
size_t upgrade_firmware_request__get_packed_size
                     (const UpgradeFirmwareRequest *message)
{
  assert(message->base.descriptor == &upgrade_firmware_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t upgrade_firmware_request__pack
                     (const UpgradeFirmwareRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &upgrade_firmware_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t upgrade_firmware_request__pack_to_buffer
                     (const UpgradeFirmwareRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &upgrade_firmware_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpgradeFirmwareRequest *
       upgrade_firmware_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpgradeFirmwareRequest *)
     protobuf_c_message_unpack (&upgrade_firmware_request__descriptor,
                                allocator, len, data);
}
void   upgrade_firmware_request__free_unpacked
                     (UpgradeFirmwareRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &upgrade_firmware_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   upgrade_firmware_response__init
                     (UpgradeFirmwareResponse         *message)
{
  static const UpgradeFirmwareResponse init_value = UPGRADE_FIRMWARE_RESPONSE__INIT;
  *message = init_value;
}
size_t upgrade_firmware_response__get_packed_size
                     (const UpgradeFirmwareResponse *message)
{
  assert(message->base.descriptor == &upgrade_firmware_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t upgrade_firmware_response__pack
                     (const UpgradeFirmwareResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &upgrade_firmware_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t upgrade_firmware_response__pack_to_buffer
                     (const UpgradeFirmwareResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &upgrade_firmware_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpgradeFirmwareResponse *
       upgrade_firmware_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpgradeFirmwareResponse *)
     protobuf_c_message_unpack (&upgrade_firmware_response__descriptor,
                                allocator, len, data);
}
void   upgrade_firmware_response__free_unpacked
                     (UpgradeFirmwareResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &upgrade_firmware_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   time_point__init
                     (TimePoint         *message)
{
  static const TimePoint init_value = TIME_POINT__INIT;
  *message = init_value;
}
size_t time_point__get_packed_size
                     (const TimePoint *message)
{
  assert(message->base.descriptor == &time_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_point__pack
                     (const TimePoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_point__pack_to_buffer
                     (const TimePoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimePoint *
       time_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimePoint *)
     protobuf_c_message_unpack (&time_point__descriptor,
                                allocator, len, data);
}
void   time_point__free_unpacked
                     (TimePoint *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   brightness__init
                     (Brightness         *message)
{
  static const Brightness init_value = BRIGHTNESS__INIT;
  *message = init_value;
}
size_t brightness__get_packed_size
                     (const Brightness *message)
{
  assert(message->base.descriptor == &brightness__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t brightness__pack
                     (const Brightness *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &brightness__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t brightness__pack_to_buffer
                     (const Brightness *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &brightness__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Brightness *
       brightness__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Brightness *)
     protobuf_c_message_unpack (&brightness__descriptor,
                                allocator, len, data);
}
void   brightness__free_unpacked
                     (Brightness *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &brightness__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   time_stamp__init
                     (TimeStamp         *message)
{
  static const TimeStamp init_value = TIME_STAMP__INIT;
  *message = init_value;
}
size_t time_stamp__get_packed_size
                     (const TimeStamp *message)
{
  assert(message->base.descriptor == &time_stamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_stamp__pack
                     (const TimeStamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_stamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_stamp__pack_to_buffer
                     (const TimeStamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_stamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimeStamp *
       time_stamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimeStamp *)
     protobuf_c_message_unpack (&time_stamp__descriptor,
                                allocator, len, data);
}
void   time_stamp__free_unpacked
                     (TimeStamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_stamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define device_information_request__field_descriptors NULL
#define device_information_request__field_indices_by_name NULL
#define device_information_request__number_ranges NULL
const ProtobufCMessageDescriptor device_information_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceInformationRequest",
  "DeviceInformationRequest",
  "DeviceInformationRequest",
  "",
  sizeof(DeviceInformationRequest),
  0,
  device_information_request__field_descriptors,
  device_information_request__field_indices_by_name,
  0,  device_information_request__number_ranges,
  (ProtobufCMessageInit) device_information_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_information_response__field_descriptors[5] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DeviceInformationResponse, mode),
    &mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_timestamps",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceInformationResponse, current_timestamps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformationResponse, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformationResponse, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInformationResponse, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_information_response__field_indices_by_name[] = {
  1,   /* field[1] = current_timestamps */
  3,   /* field[3] = id */
  0,   /* field[0] = mode */
  2,   /* field[2] = name */
  4,   /* field[4] = version */
};
static const ProtobufCIntRange device_information_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor device_information_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceInformationResponse",
  "DeviceInformationResponse",
  "DeviceInformationResponse",
  "",
  sizeof(DeviceInformationResponse),
  5,
  device_information_response__field_descriptors,
  device_information_response__field_indices_by_name,
  1,  device_information_response__number_ranges,
  (ProtobufCMessageInit) device_information_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lighting_schedule_request__field_descriptors[1] =
{
  {
    "points",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LightingScheduleRequest, n_points),
    offsetof(LightingScheduleRequest, points),
    &time_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lighting_schedule_request__field_indices_by_name[] = {
  0,   /* field[0] = points */
};
static const ProtobufCIntRange lighting_schedule_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor lighting_schedule_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LightingScheduleRequest",
  "LightingScheduleRequest",
  "LightingScheduleRequest",
  "",
  sizeof(LightingScheduleRequest),
  1,
  lighting_schedule_request__field_descriptors,
  lighting_schedule_request__field_indices_by_name,
  1,  lighting_schedule_request__number_ranges,
  (ProtobufCMessageInit) lighting_schedule_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_scene_request__field_descriptors[1] =
{
  {
    "scene",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SetSceneRequest, scene),
    &scene__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_scene_request__field_indices_by_name[] = {
  0,   /* field[0] = scene */
};
static const ProtobufCIntRange set_scene_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor set_scene_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetSceneRequest",
  "SetSceneRequest",
  "SetSceneRequest",
  "",
  sizeof(SetSceneRequest),
  1,
  set_scene_request__field_descriptors,
  set_scene_request__field_indices_by_name,
  1,  set_scene_request__number_ranges,
  (ProtobufCMessageInit) set_scene_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_scene_response__field_descriptors[1] =
{
  {
    "scene",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GetSceneResponse, scene),
    &scene__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_scene_response__field_indices_by_name[] = {
  0,   /* field[0] = scene */
};
static const ProtobufCIntRange get_scene_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_scene_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetSceneResponse",
  "GetSceneResponse",
  "GetSceneResponse",
  "",
  sizeof(GetSceneResponse),
  1,
  get_scene_response__field_descriptors,
  get_scene_response__field_indices_by_name,
  1,  get_scene_response__number_ranges,
  (ProtobufCMessageInit) get_scene_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor effect__field_descriptors[2] =
{
  {
    "duration",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Effect, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamps",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Effect, n_timestamps),
    offsetof(Effect, timestamps),
    &time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned effect__field_indices_by_name[] = {
  0,   /* field[0] = duration */
  1,   /* field[1] = timestamps */
};
static const ProtobufCIntRange effect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor effect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Effect",
  "Effect",
  "Effect",
  "",
  sizeof(Effect),
  2,
  effect__field_descriptors,
  effect__field_indices_by_name,
  1,  effect__number_ranges,
  (ProtobufCMessageInit) effect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define upgrade_firmware_request__field_descriptors NULL
#define upgrade_firmware_request__field_indices_by_name NULL
#define upgrade_firmware_request__number_ranges NULL
const ProtobufCMessageDescriptor upgrade_firmware_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UpgradeFirmwareRequest",
  "UpgradeFirmwareRequest",
  "UpgradeFirmwareRequest",
  "",
  sizeof(UpgradeFirmwareRequest),
  0,
  upgrade_firmware_request__field_descriptors,
  upgrade_firmware_request__field_indices_by_name,
  0,  upgrade_firmware_request__number_ranges,
  (ProtobufCMessageInit) upgrade_firmware_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor upgrade_firmware_response__field_descriptors[2] =
{
  {
    "is_latest_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(UpgradeFirmwareResponse, is_latest_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UpgradeFirmwareResponse, current_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned upgrade_firmware_response__field_indices_by_name[] = {
  1,   /* field[1] = current_version */
  0,   /* field[0] = is_latest_version */
};
static const ProtobufCIntRange upgrade_firmware_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor upgrade_firmware_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UpgradeFirmwareResponse",
  "UpgradeFirmwareResponse",
  "UpgradeFirmwareResponse",
  "",
  sizeof(UpgradeFirmwareResponse),
  2,
  upgrade_firmware_response__field_descriptors,
  upgrade_firmware_response__field_indices_by_name,
  1,  upgrade_firmware_response__number_ranges,
  (ProtobufCMessageInit) upgrade_firmware_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor time_point__field_descriptors[3] =
{
  {
    "hh",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimePoint, hh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mm",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimePoint, mm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brightness",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TimePoint, brightness),
    &brightness__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_point__field_indices_by_name[] = {
  2,   /* field[2] = brightness */
  0,   /* field[0] = hh */
  1,   /* field[1] = mm */
};
static const ProtobufCIntRange time_point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor time_point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimePoint",
  "TimePoint",
  "TimePoint",
  "",
  sizeof(TimePoint),
  3,
  time_point__field_descriptors,
  time_point__field_indices_by_name,
  1,  time_point__number_ranges,
  (ProtobufCMessageInit) time_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor brightness__field_descriptors[7] =
{
  {
    "white",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, white),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warm_white",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, warm_white),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "red",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, red),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "green",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "royal_blue",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, royal_blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ultra_violet",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Brightness, ultra_violet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned brightness__field_indices_by_name[] = {
  4,   /* field[4] = blue */
  3,   /* field[3] = green */
  2,   /* field[2] = red */
  5,   /* field[5] = royal_blue */
  6,   /* field[6] = ultra_violet */
  1,   /* field[1] = warm_white */
  0,   /* field[0] = white */
};
static const ProtobufCIntRange brightness__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor brightness__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Brightness",
  "Brightness",
  "Brightness",
  "",
  sizeof(Brightness),
  7,
  brightness__field_descriptors,
  brightness__field_indices_by_name,
  1,  brightness__number_ranges,
  (ProtobufCMessageInit) brightness__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor time_stamp__field_descriptors[2] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brightness",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TimeStamp, brightness),
    &brightness__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_stamp__field_indices_by_name[] = {
  1,   /* field[1] = brightness */
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange time_stamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor time_stamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimeStamp",
  "TimeStamp",
  "TimeStamp",
  "",
  sizeof(TimeStamp),
  2,
  time_stamp__field_descriptors,
  time_stamp__field_indices_by_name,
  1,  time_stamp__number_ranges,
  (ProtobufCMessageInit) time_stamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue scene__enum_values_by_number[1] =
{
  { "SCENE_UNSPECIFIED", "SCENE__SCENE_UNSPECIFIED", 0 },
};
static const ProtobufCIntRange scene__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex scene__enum_values_by_name[1] =
{
  { "SCENE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor scene__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Scene",
  "Scene",
  "Scene",
  "",
  1,
  scene__enum_values_by_number,
  1,
  scene__enum_values_by_name,
  1,
  scene__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue command_code__enum_values_by_number[4] =
{
  { "COMMAND_CODE_UNSPECIFIED", "COMMAND_CODE__COMMAND_CODE_UNSPECIFIED", 0 },
  { "COMMAND_GET_PROPERTIES", "COMMAND_CODE__COMMAND_GET_PROPERTIES", 1 },
  { "COMMAND_SET_LIGHTING", "COMMAND_CODE__COMMAND_SET_LIGHTING", 5 },
  { "COMMAND_UPGRADE_FIRMWARE", "COMMAND_CODE__COMMAND_UPGRADE_FIRMWARE", 6 },
};
static const ProtobufCIntRange command_code__value_ranges[] = {
{0, 0},{5, 2},{0, 4}
};
static const ProtobufCEnumValueIndex command_code__enum_values_by_name[4] =
{
  { "COMMAND_CODE_UNSPECIFIED", 0 },
  { "COMMAND_GET_PROPERTIES", 1 },
  { "COMMAND_SET_LIGHTING", 2 },
  { "COMMAND_UPGRADE_FIRMWARE", 3 },
};
const ProtobufCEnumDescriptor command_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CommandCode",
  "CommandCode",
  "CommandCode",
  "",
  4,
  command_code__enum_values_by_number,
  4,
  command_code__enum_values_by_name,
  2,
  command_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue mode__enum_values_by_number[3] =
{
  { "MODE_UNSPECIFIED", "MODE__MODE_UNSPECIFIED", 0 },
  { "MODE_MANUAL", "MODE__MODE_MANUAL", 1 },
  { "MODE_SCHEDULE", "MODE__MODE_SCHEDULE", 2 },
};
static const ProtobufCIntRange mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex mode__enum_values_by_name[3] =
{
  { "MODE_MANUAL", 1 },
  { "MODE_SCHEDULE", 2 },
  { "MODE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Mode",
  "Mode",
  "Mode",
  "",
  3,
  mode__enum_values_by_number,
  3,
  mode__enum_values_by_name,
  1,
  mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue led__enum_values_by_number[8] =
{
  { "LED_UNSPECIFIED", "LED__LED_UNSPECIFIED", 0 },
  { "LED_WHITE", "LED__LED_WHITE", 1 },
  { "LED_WARM_WHITE", "LED__LED_WARM_WHITE", 2 },
  { "LED_RED", "LED__LED_RED", 3 },
  { "LED_GREEN", "LED__LED_GREEN", 4 },
  { "LED_BLUE", "LED__LED_BLUE", 5 },
  { "LED_ROYAL_BLUE", "LED__LED_ROYAL_BLUE", 6 },
  { "LED_ULTRA_VIOLET", "LED__LED_ULTRA_VIOLET", 7 },
};
static const ProtobufCIntRange led__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex led__enum_values_by_name[8] =
{
  { "LED_BLUE", 5 },
  { "LED_GREEN", 4 },
  { "LED_RED", 3 },
  { "LED_ROYAL_BLUE", 6 },
  { "LED_ULTRA_VIOLET", 7 },
  { "LED_UNSPECIFIED", 0 },
  { "LED_WARM_WHITE", 2 },
  { "LED_WHITE", 1 },
};
const ProtobufCEnumDescriptor led__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "LED",
  "LED",
  "LED",
  "",
  8,
  led__enum_values_by_number,
  8,
  led__enum_values_by_name,
  1,
  led__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
